### PR TITLE
Fix/invalid packet

### PR DESCRIPTION
**Pull request by supertom01**
At this moment when one is running testRobot.py with a programmer connected onto a robot, the robot returns feedback that is not recognized by REMParser.py causing the script the crash. 

I do not know why this is happening, nor on how to prevent it. So for now I just empty the buffer and start again. Perhaps @emielsteerneman knows what is wrong? I assume the rewrite broke something.

### CODE REVIEW

**Comment by supertom01** [comment]
Whoops I might have included some test functions for pid testing by accident... However, the latest commit is the hotfix

**Comment by emielsteerneman** [comment]
What's with all the files in the proto folder?

**Comment by supertom01** [comment]
That's a very good question... 

I have no idea 😅
I'll look at it somewhere this week

**Comment by JornJorn** [comment]
As this hasn't happened the entire year so far (and remparser has undergone a little facelift), I think it's save to assume this is fixed already. Will close for now.

**Pull request closed without merging**
